version: '3.7'

services:
  device-onvif-camera:
    image: edgexfoundry/device-onvif-camera${ARCH}:${DEVICE_ONVIFCAM_VERSION}
    ports:
      - "127.0.0.1:59984:59984"
    container_name: edgex-device-onvif-camera
    hostname: edgex-device-onvif-camera
    read_only: true
    restart: always
    networks:
      - edgex-network
    env_file:
      - common.env
      - device-common.env
    environment:
      SERVICE_HOST: edgex-device-onvif-camera
      MESSAGEQUEUE_HOST: edgex-redis
    depends_on:
      - consul
      - data
      - metadata
    security_opt:
      - no-new-privileges:true
    user: "${EDGEX_USER}:${EDGEX_GROUP}"
